# Generated by Django 4.2.2 on 2023-06-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blooddonner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDonner',
            new_name='BloodDoner',
        ),
    ]
